### ISSUE TITLE
The browser doesn't work

### ISSUE THREAD

**Issue by azarins1** [Shuzhengz/bbbbrowser#1]
I don't know why but the browser is not working at all :(

**Comment by Shuzhengz** [comment]
Lmao

**Comment by Shuzhengz** [comment]
Well it's supposed to start and display whatever website u put in in a very weird way

**Comment by Shuzhengz** [comment]
@azarins1 pull from main and try again

**Comment by azarins1** [comment]
See I don't have java installed so I don't even know what it does rn lmfao
I gotta install java first b4 I try for my first time
